background: true
background_color:
    R: 22
    G: 22
    B: 22
default_cursor: "#"
default_color:
    R: 255
    G: 255
    B: 255

pointer: "❯"
pointer_color:
    R: 170
    G: 170
    B: 170

fill_cursor: "\U000F0266"

symbols:
    3:
        2: "┌"
        4: "├"
        6: "┬"
        8: "─"
        9: "┐"
    5:
        2: "└"
        4: "┤"
        6: "┴"
        8: "│"
        9: "┘"
        11: "┼"
    7:
        2: "┏"
        4: "┣"
        6: "┳"
        8: "━"
        9: "┓"
    9:
        2: "┗"
        4: "┫"
        6: "┻"
        8: "┃"
        9: "┛"
        11: "╋"
    11:
        2: "╭"
        4: "╮"
        6: "╯"
        8: "╰"
    13:
        2: "░"
        4: "▒"
        6: "▓"
        8: "█"

show_folder: true
show_hidden_folder: false
image_save_directory: './'
image_save_name_format: "termPaint_01-02-2006_15:04:05.txt"
notifications:
    set_symbol: true
    error: true
    save_image: true
    load_image_size_errors: true
notification_time: 200