default_cursor: "#"
default_color:
    R: 255
    G: 255
    B: 255

pointer: "❯"
pointer_color:
    R: 170
    G: 170
    B: 170

symbols:
    1:
        2: "┌"
        4: "├"
        6: "┬"
        8: "─"
        9: "┐"
    3:
        2: "└"
        4: "┤"
        6: "┴"
        8: "│"
        9: "┘"
        11: "┼"
    5:
        2: "┏"
        4: "┣"
        6: "┳"
        8: "━"
        9: "┓"
    7:
        2: "┗"
        4: "┫"
        6: "┻"
        8: "┃"
        9: "┛"
        11: "╋"
    9:
        2: "╭"
        4: "╮"
        6: "╯"
        8: "╰"
    11:
        2: "░"
        4: "▒"
        6: "▓"
        8: "█"

show_folder: true
show_hidden_folder: false
image_save_directory: './'
image_save_name_format: "termPaint_01-02-2006_15:04:05.txt"
